In [1]:
import torch
torch.cuda.is_available()

True

In [15]:
# On peut creer directement des tenseurs a base de list et numpy

my_list = [[1, 2, 3], [4, 5, 6]]
my_list_as_tensor = torch.tensor(my_list, device='cuda', dtype=torch.float32)
# help(my_list_as_tensor)

# Cree un tenseur de meme taille que my_list_as_tensor
tensor_from_tensor = torch.ones_like(my_list_as_tensor, device='cuda', dtype=torch.float32)
print(tensor_from_tensor)

tensor([[1., 1., 1.],
        [1., 1., 1.]], device='cuda:0')


In [18]:
print(torch.cat((my_list_as_tensor,tensor_from_tensor), dim=1))
print(my_list_as_tensor @ tensor_from_tensor.T)
print(my_list_as_tensor * tensor_from_tensor)

tensor([[1., 2., 3., 1., 1., 1.],
        [4., 5., 6., 1., 1., 1.]], device='cuda:0')
tensor([[ 6.,  6.],
        [15., 15.]], device='cuda:0')
tensor([[1., 2., 3.],
        [4., 5., 6.]], device='cuda:0')


In [19]:
from __future__ import print_function
import torch
import numpy as np

In [21]:
import torch

# 1. Données d'entraînement
X = torch.tensor([[1.0, 2.0]])  # Entrée (1 exemple, 2 features)
Y = torch.tensor([[5.0]])       # Cible (La réponse que le modèle doit apprendre)

# 2. Poids et Biais (Les paramètres du modèle)
# requires_grad=True est essentiel pour la rétropropagation
w = torch.tensor([[0.5], [0.5]], requires_grad=True) # Poids (2x1)
b = torch.tensor([[0.1]], requires_grad=True)        # Biais (1x1)

# Hyperparamètres
learning_rate = 0.01  # Le taux d'apprentissage (pas d'ajustement)

In [22]:
# Multiplier les entrées par les poids, puis ajouter le biais
Y_pred = torch.matmul(X, w) + b
print(f"Prédiction initiale (Y_pred): {Y_pred.item():.4f}")
# Pour notre exemple : (1*0.5 + 2*0.5) + 0.1 = 1.6

Prédiction initiale (Y_pred): 1.6000


In [24]:
loss = (Y_pred - Y).pow(2).mean()  # Calcul de la perte (MSE)
print(f"Perte initiale: {loss.item():.4f}")

loss.backward()  # Calcul des gradients
print(f"Gradient w: {w.grad.squeeze().numpy()}")
print(f"Gradient b: {b.grad.item():.4f}")

Perte initiale: 11.5600
Gradient w: [ -6.8 -13.6]
Gradient b: -6.8000


In [25]:
with torch.no_grad():
    # Mise à jour des poids w
    w -= learning_rate * w.grad
    # Mise à jour du biais b
    b -= learning_rate * b.grad
    
    # Réinitialisation des gradients pour la prochaine itération
    w.grad.zero_()
    b.grad.zero_()

In [26]:
print(f"\nNouveaux poids (w) après une étape: \n{w}")

# Nouvelle prédiction avec les poids ajustés
Y_pred_new = torch.matmul(X, w) + b
loss_new = (Y_pred_new - Y).pow(2).sum()

print(f"Nouvelle prédiction: {Y_pred_new.item():.4f}")
print(f"Nouvelle Perte: {loss_new.item():.4f}")


Nouveaux poids (w) après une étape: 
tensor([[0.5680],
        [0.6360]], requires_grad=True)
Nouvelle prédiction: 2.0080
Nouvelle Perte: 8.9521


In [3]:
x = torch.tensor([])
x

tensor([])

In [4]:
x = torch.tensor([1, 2, 3], dtype=torch.float32)
x

tensor([1., 2., 3.])

In [5]:
x = torch.ones((3,2), dtype=torch.float32)
x

tensor([[1., 1.],
        [1., 1.],
        [1., 1.]])

In [6]:
y = torch.randn((3,2), dtype=torch.float32)
y

tensor([[-0.2363, -0.2648],
        [ 1.3961,  1.1609],
        [ 0.2932, -1.5713]])

In [7]:
x = torch.stack([torch.ones((3,2), dtype=torch.float32) for _ in range(5)])
x

tensor([[[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]],

        [[1., 1.],
         [1., 1.],
         [1., 1.]]])

In [8]:
z = torch.stack([torch.mul(x, torch.tensor(_)) for _ in y])
z

/tmp/ipykernel_414432/3367320419.py:1: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.detach().clone() or sourceTensor.detach().clone().requires_grad_(True), rather than torch.tensor(sourceTensor).
  z = torch.stack([torch.mul(x, torch.tensor(_)) for _ in y])


tensor([[[[-0.2363, -0.2648],
          [-0.2363, -0.2648],
          [-0.2363, -0.2648]],

         [[-0.2363, -0.2648],
          [-0.2363, -0.2648],
          [-0.2363, -0.2648]],

         [[-0.2363, -0.2648],
          [-0.2363, -0.2648],
          [-0.2363, -0.2648]],

         [[-0.2363, -0.2648],
          [-0.2363, -0.2648],
          [-0.2363, -0.2648]],

         [[-0.2363, -0.2648],
          [-0.2363, -0.2648],
          [-0.2363, -0.2648]]],


        [[[ 1.3961,  1.1609],
          [ 1.3961,  1.1609],
          [ 1.3961,  1.1609]],

         [[ 1.3961,  1.1609],
          [ 1.3961,  1.1609],
          [ 1.3961,  1.1609]],

         [[ 1.3961,  1.1609],
          [ 1.3961,  1.1609],
          [ 1.3961,  1.1609]],

         [[ 1.3961,  1.1609],
          [ 1.3961,  1.1609],
          [ 1.3961,  1.1609]],

         [[ 1.3961,  1.1609],
          [ 1.3961,  1.1609],
          [ 1.3961,  1.1609]]],


        [[[ 0.2932, -1.5713],
          [ 0.2932, -1.5713],
          [ 0.29

Calcul de ∂o/∂x :

1) o = mean(z) = (1/4) * Σ(zij)
2) z = (3 * y²)/x
3) y = x + 5

Donc :
∂o/∂x = (1/4) * Σ(∂z/∂x)
où ∂z/∂x = 3 * ((∂y²/∂x)/x - y²/x²)
et ∂y²/∂x = 2y * (∂y/∂x) = 2y * 1 = 2y

En remplaçant les valeurs :
y = x + 5 = 1 + 5 = 6
y² = 36
∂y²/∂x = 2 * 6 = 12

∂z/∂x = 3 * (12/1 - 36/1) = 3 * (-24) = -72

Donc ∂o/∂x = -72/4 = -18


In [10]:

# Déclaration et initialisation d'un Tensor x de taille 2×2
x = torch.ones((2, 2), dtype=torch.float32, requires_grad=True)
print('x:', x)

# Déclaration de y = x + 5
y = x + 5
print('y:', y)

# Déclaration de z = (3 × y²)/x
z = (3 * y**2) / x
print('z:', z)

# Déclaration de o = mean(z)
o = z.mean()
print('o:', o)

# Calcul du gradient avec autograd
o.backward()
print('Gradient calculé par autograd (∂o/∂x):', x.grad)


x: tensor([[1., 1.],
        [1., 1.]], requires_grad=True)
y: tensor([[6., 6.],
        [6., 6.]], grad_fn=<AddBackward0>)
z: tensor([[108., 108.],
        [108., 108.]], grad_fn=<DivBackward0>)
o: tensor(108., grad_fn=<MeanBackward0>)
Gradient calculé par autograd (∂o/∂x): tensor([[-18., -18.],
        [-18., -18.]])


In [ ]:
torch.nn.Conv1d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=0)



In [15]:
import torch.nn as nn
import torch.nn.functional as F

class myNet(nn.Module):
    def __init__(self):
        super(myNet, self).__init__()
        self.conv1 = nn.Conv1d(in_channels=1, out_channels=2, kernel_size=3, stride=1, padding=0)
        self.conv2 = nn.Conv1d(in_channels=2, out_channels=4, kernel_size=3, stride=1, padding=0)

    def forward(self, x):
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.relu(x)
        x = self.pool(x)
        x = self.conv1(x)
        x = F.relu(x)
        x = self.conv2(x)
        x = F.relu(x)
        return x
    
net = myNet()
print(net)

input = x
out = net(input)
out

myNet(
  (conv1): Conv1d(1, 2, kernel_size=(3,), stride=(1,))
  (conv2): Conv1d(2, 4, kernel_size=(3,), stride=(1,))
)


RuntimeError: Given groups=1, weight of size [2, 1, 3], expected input[1, 2, 2] to have 1 channels, but got 2 channels instead